# Generated by Django 3.2.8 on 2021-10-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
