# Generated by Django 3.2.8 on 2021-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=15)),
                ('Surname', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=6)),
                ('Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Surname',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Patients',
            field=models.ManyToManyField(to='api.Patient'),
        ),
    ]
