# Generated by Django 3.2.8 on 2021-10-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211022_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Patients',
        ),
        migrations.AddField(
            model_name='user',
            name='PatientList',
            field=models.ManyToManyField(default=list, to='api.Patient'),
        ),
    ]
