# Generated by Django 3.2.8 on 2021-10-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211022_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=15)),
                ('Surname', models.CharField(max_length=15)),
                ('Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='patient',
            name='DoctorId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
            preserve_default=False,
        ),
    ]
