# Generated by Django 3.2.8 on 2021-10-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211025_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Job',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='LastDiagnosis',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='LastScore',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='patient',
            name='MarritalStatus',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('VisitId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Diagnosis', models.CharField(max_length=30)),
                ('Score', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
